In [1]:
import pandas as pd

df_games = pd.read_csv(r"C:\myProject\pythonNotebooks\ICD_NBA_Proj_UFPB\DataSets\games.csv")

df_games

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,23.0,53.0,1610612750,113.0,0.422,0.875,0.357,21.0,46.0,0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,20.0,46.0,1610612739,91.0,0.419,0.824,0.208,19.0,40.0,1
2,2022-03-12,22101007,Final,1610612759,1610612754,2021,1610612759,108.0,0.412,0.813,...,28.0,52.0,1610612754,119.0,0.489,1.000,0.389,23.0,47.0,0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,33.0,55.0,1610612749,109.0,0.413,0.696,0.386,27.0,39.0,1
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,32.0,39.0,1610612761,127.0,0.471,0.760,0.387,28.0,50.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25791,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
25792,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
25793,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
25794,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
25795,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [2]:
df_games.loc[df_games["SEASON"] == 2021]

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-03-12,22101005,Final,1610612748,1610612750,2021,1610612748,104.0,0.398,0.760,...,23.0,53.0,1610612750,113.0,0.422,0.875,0.357,21.0,46.0,0
1,2022-03-12,22101006,Final,1610612741,1610612739,2021,1610612741,101.0,0.443,0.933,...,20.0,46.0,1610612739,91.0,0.419,0.824,0.208,19.0,40.0,1
2,2022-03-12,22101007,Final,1610612759,1610612754,2021,1610612759,108.0,0.412,0.813,...,28.0,52.0,1610612754,119.0,0.489,1.000,0.389,23.0,47.0,0
3,2022-03-12,22101008,Final,1610612744,1610612749,2021,1610612744,122.0,0.484,0.933,...,33.0,55.0,1610612749,109.0,0.413,0.696,0.386,27.0,39.0,1
4,2022-03-12,22101009,Final,1610612743,1610612761,2021,1610612743,115.0,0.551,0.750,...,32.0,39.0,1610612761,127.0,0.471,0.760,0.387,28.0,50.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071,2021-10-04,12100007,Final,1610612759,1610612762,2021,1610612759,111.0,0.465,0.760,...,22.0,60.0,1610612762,85.0,0.317,0.600,0.233,14.0,47.0,1
1072,2021-10-04,12100008,Final,1610612757,1610612744,2021,1610612757,107.0,0.446,0.773,...,21.0,53.0,1610612744,121.0,0.420,0.765,0.348,32.0,47.0,0
1073,2021-10-04,12100009,Final,1610612758,1610612756,2021,1610612758,117.0,0.473,0.684,...,22.0,51.0,1610612756,106.0,0.467,0.846,0.314,24.0,38.0,1
1074,2021-10-04,12100010,Final,1610612746,1610612743,2021,1610612746,103.0,0.432,0.760,...,26.0,52.0,1610612743,102.0,0.430,0.621,0.270,20.0,45.0,1
1075,2021-10-03,12100001,Final,1610612747,1610612751,2021,1610612747,97.0,0.364,0.688,...,17.0,41.0,1610612751,123.0,0.483,0.725,0.417,20.0,54.0,0

In [3]:
df_teams = pd.read_csv(r"C:\myProject\pythonNotebooks\ICD_NBA_Proj_UFPB\DataSets\teams.csv",index_col= False ,usecols= [1, 5])

df_teams

       TEAM_ID       NICKNAME
0   1610612737          Hawks
1   1610612738        Celtics
2   1610612740       Pelicans
3   1610612741          Bulls
4   1610612742      Mavericks
5   1610612743        Nuggets
6   1610612745        Rockets
7   1610612746       Clippers
8   1610612747         Lakers
9   1610612748           Heat
10  1610612749          Bucks
11  1610612750   Timberwolves
12  1610612751           Nets
13  1610612752         Knicks
14  1610612753          Magic
15  1610612754         Pacers
16  1610612755          76ers
17  1610612756           Suns
18  1610612757  Trail Blazers
19  1610612758          Kings
20  1610612759          Spurs
21  1610612760        Thunder
22  1610612761        Raptors
23  1610612762           Jazz
24  1610612763      Grizzlies
25  1610612764        Wizards
26  1610612765        Pistons
27  1610612766        Hornets
28  1610612739      Cavaliers
29  1610612744       Warriors

In [4]:
df_teams.set_index('TEAM_ID').to_dict()['NICKNAME']

{1610612737: 'Hawks',
 1610612738: 'Celtics',
 1610612740: 'Pelicans',
 1610612741: 'Bulls',
 1610612742: 'Mavericks',
 1610612743: 'Nuggets',
 1610612745: 'Rockets',
 1610612746: 'Clippers',
 1610612747: 'Lakers',
 1610612748: 'Heat',
 1610612749: 'Bucks',
 1610612750: 'Timberwolves',
 1610612751: 'Nets',
 1610612752: 'Knicks',
 1610612753: 'Magic',
 1610612754: 'Pacers',
 1610612755: '76ers',
 1610612756: 'Suns',
 1610612757: 'Trail Blazers',
 1610612758: 'Kings',
 1610612759: 'Spurs',
 1610612760: 'Thunder',
 1610612761: 'Raptors',
 1610612762: 'Jazz',
 1610612763: 'Grizzlies',
 1610612764: 'Wizards',
 1610612765: 'Pistons',
 1610612766: 'Hornets',
 1610612739: 'Cavaliers',
 1610612744: 'Warriors'}